### ISSUE TITLE
Meta Tracker

### ISSUE THREAD

**Issue by the-spectator** [the-spectator/git_my_life#2]
All tasks:
- [ ] RFC
- [ ] PRD
- [ ] Golang init
- [ ] Golang test suite
- [ ] Golang CLI
  - [ ] init
  - [ ] help
  - [ ] server
  - [ ] push
  - [ ] pull
- [ ] Vue app init
- [ ] Vue app markdown
- [ ] Vue app embedded
- [ ] Distribute it as brew formula
